routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/admin-index', function () { 
//     return view('admin/index');
// });


Route::get('/admin-Login', function () { 
    return view('admin/login/login');
});



Route::get('/signup', function () {
    return view('visitor/signup');
});



Route::get('/contact', function () {
    return view('visitor/contact/contact');
});


// Route::group(['prefix' => 'manufacturers'], function() {
    Route::get('/', 'OthersSectionController@index')->name('dashboard');
    Route::get('/signin', 'OthersSectionController@signin')->name('signin');
    Route::get('/register', 'OthersSectionController@register')->name('register');
    Route::get('/contact', 'OthersSectionController@contact')->name('contact');
    Route::get('/admin-index', 'OthersSectionController@adminindex')->name('admin.index');


    Route::group(['prefix' => '/post'], function() {
    Route::resource('/', 'PostController');
  
   
});

    // Route::get('/{id}/edit', 'ManufacturerController@edit')->name('manufacturers.edit');
    // Route::post('/{id}/update', 'ManufacturerController@update')->name('manufacturers.update');
    // Route::get('/{id}/delete', 'ManufacturerController@delete')->name('manufacturers.delete');

// });

// Faculty
 Route::group(['prefix' => '/admin'], function() {
 Route::resource('/faculty', 'Admin\FacultyController');  
 });
 // department
 Route::group(['prefix' => '/admin'], function() {
 Route::resource('/department', 'Admin\DepartmentController');  
 });
 // class
 Route::group(['prefix' => '/admin'], function() {
 Route::resource('/class', 'Admin\ClassController');  
 });
  // subject
 Route::group(['prefix' => '/admin'], function() {
 Route::resource('/subject', 'Admin\SubjectController');  
 });
 //message
  Route::group(['prefix' => '/admin'], function() {
 Route::resource('/message', 'Admin\MessageController');  
 });
 // manage
 Route::get('/admin/postList', 'Admin\ManageController@postList')->name('admin.postList');
 Route::DELETE('/admin/postList/{id}/delete', 'Admin\ManageController@postDelete')->name('admin.postDelete');

 Route::get('/admin/tutorList', 'Admin\ManageController@tutorList')->name('admin.tutorList');
 Route::DELETE('/admin/tutorList/{id}/delete', 'Admin\ManageController@tutorDelete')->name('admin.tutorDelete');

Route::get('/ajax/division', 'Admin\AddressController@division');
Route::get('/ajax/district', 'Admin\AddressController@district');
Route::get('/ajax/upazila', 'Admin\AddressController@upazila');
Route::get('/ajax/area', 'Admin\AddressController@area');


 //Route::get('/admin-LoginPage', 'Auth\LoginController@login_page');

//admin login route






// Route::get('/sms','SmsController@sms');
Route::get('/code-verify','VerifyController@codeverify');
Route::post('/post-verify','VerifyController@postVerify')->name('post.verify');
Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

// Tutor profile
Auth::routes();
Route::middleware('auth')->group(function () {

Route::group(['prefix' => '/'], function() {
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/tutorProfile', 'TutorProfileController');
Route::get('/tutorProfileList', 'TutorProfileController@postList')->name('tutorProfile.postList'); 
Route::get('/postView/{id}', 'PostController@show')->name('post.postView');  
});

  Route::get('/admin-LoginPage', 'Auth\LoginController@login_page')->name('admin.adminLogin');
  Route::get('/admin-index', 'Auth\LoginController@admin_index')->name('admin.index');

});

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $guarded=[];
}

app/Http/Controllers/API/DepartmentController.php
<?php

namespace App\Http\Controllers\API;
use App\Http\Controllers\API\BaseController as BaseController;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Department;

class DepartmentController extends BaseController
{
	public function department()
	 {
     $departments = Department::all();       
     return $this->sendResponse($departments->toArray(), 'Department retrieved successfully.');
     }
}

app/Http/Controllers/Admin/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Department;
use Validator;
class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments=Department::orderBy('id', 'DESC')->get();
        return view('admin.department.index',compact('departments'))->with('no',1);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $input = $request->all();
       $validator = Validator::make($input, [
            'name' => 'required|string|max:255',
         ]); 
       if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }              
        $departments = Department::create($input);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $department = Department::findOrFail($id);
        $department->delete();
        return redirect()->back()->withSuccess('IT SUCCESSFULLY DELETED!');
    }
}

resources/views/admin/department/index.blade.php
@extends('admin-layout.master')
@section('content')

<link rel="stylesheet" href="assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>Department</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Best Tutor</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Add All Department Name</li>
                            </ol>
                        </nav>
                    </div>            
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        <a href="javascript:void(0);" class="btn btn-sm btn-primary" title="">Dashboard</a>
                        <a href="#" class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                    </div>
                </div>
            </div>
    <form role="form" action="{{route('department.store')}}" method="POST" enctype="multipart/form-data">
     @csrf
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12">
                    <div class="card">
                        <div class="body">
                            <div class="row">

                                      @if ($errors->any())
                                            <div class="alert alert-warning alert-dismissible" role="alert">
                                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                                @if ($errors->count() == 1)
                                                   {{$errors->first()}}
                                                @else
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                                @endif
                                            </div>
                                    @endif


                                <div class="row col-lg-12">
                                    <div class="col-lg-3">
                                    <label for="basic-url">Add Department Name:</label>
                                    </div>
                                    <div class="col-lg-7">
                                    <div class="form-group">                                   
                                        <input type="text" name="name" class="form-control" placeholder="Example: CSE">
                                    </div>
                                    </div>
                                </div>
                            </div><br>
                            <div class="row">
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-primary">ADD</button>
                                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">RESET</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           </form> 
        </div>

 <link rel="stylesheet" href="{{asset('admin/assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css')}}">
<!-- css for data tables only -->
 <div class="col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2>All Department Name</h2>
                            <ul class="header-dropdown dropdown">
                                
                                <li><a href="javascript:void(0);" class="full-screen"><i class="icon-frame"></i></a></li>
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another Action</a></li>
                                        <li><a href="javascript:void(0);">Something else</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                           <th>Serial No.</th>
                                           <th>Name</th>
                                           <th>Action</th>
                                       
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                           <th>Serial No.</th>
                                           <th>Name</th>
                                           <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach($departments as $department)
                                        <tr>
                                           <td>{{$no++}}</td>
                                           <td>{{$department->name}}</td>
                                           <td>
                                            <form id="delete-form-{{ $department->id }}" action="{{ route('department.destroy',[$department->id]) }}" style="display: none;" method="POST">
                                               {{csrf_field()}}company
                                               {{ method_field('DELETE') }}
                                           </form>

                                      <button type="button" class="btn btn-danger" title="Delete" onclick="if(confirm('Are you sure? You want to delete this?')){
                                           event.preventDefault();
                                           document.getElementById('delete-form-{{ $department->id }}').submit();
                                       }else {
                                           event.preventDefault();
                                               }">Delete
                                      </button> 
                                          </td>
                                        </tr>
                                        @endforeach                                       
                                       </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
    </div>

@endsection